# Shell Theme
ZSH_THEME="agnoster"

# Default User
DEFAULT_USER="misigno"

# . _ and - will be interchangeable
HYPHEN_INSENSITIVE="true"

# Disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Disable colors in `ls`
DISABLE_LS_COLORS="true"

# Disable auto-setting terminal title
# DISABLE_AUTO_TITLE="true"

# Enable command auto-correction
# ENABLE_CORRECTION="true"

# Show red dots while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Timestamp format 
HIST_STAMPS="yyyy-mm-dd"

# Plugins
plugins=(
  git
  zsh-autosuggestions
)

# Load oh-my-zsh
export ZSH=/home/misigno/.oh-my-zsh
source $ZSH/oh-my-zsh.sh
source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

# Load alias file
source $ZSH/aliasFile.sh

# Start Directory
cd /mnt/BNK/Sync

# Run Tmux
if [ -z "$TMUX" ]
  then tmux
fi

