#!/bin/bash

main() {
  local session_name="$1"

  tmux has-session -t "$session_name" 2>/dev/null

  if [[ "$?" == 0 ]]; then
    # If there's already a session, switch to it
    tmux switch-client -t "$session_name"
  else
    # If there's no session, create one
    bash "$TSESSIONS/${session_name}.session"
    # Then switch to it
    tmux switch-client -t "$session_name"
  fi
}

main "$@"

