#!/bin/bash

#----------------
# Name          : switch_to_session
# Description   : Simplifies switching between TMUX session
# Author        : E Fournier
# Dependencies  : tmux
#----------------

main() {
  local session_file="$1"
  local session_name="${session_file%%_*}"

  tmux has-session -t "$session_name" 2>/dev/null

  if [[ "$?" == 0 ]]; then
    # If there's already a session, switch to it
    tmux switch-client -t "$session_name"
  else
    # If there's no session, create one
    bash "$TSESSIONS/${session_file}.session"
    # Then switch to it
    tmux switch-client -t "$session_name"
  fi
}

main "$@"

