#!/bin/bash

#----------------
# Name          : backup_snc
# Description   : Zips contents of the snc directory to an external device for backup
# Author        : E Fournier
# Dependencies  : zip
# Example Usage : ./backup_snc extA
#----------------

navigate_to_sync_dir() {
  local sync_dir="$1"

  cd "$sync_dir"
}

navigate_to_starting_dir() {
  local starting_dir="$1"

  cd "$starting_dir"
}

try_delete_preexisting_zip() {
  local zip_location="$1"

  rm -rf "$zip_location"
}

zip_snc_dir() {
  local zip_location="$1"

  zip -r "$zip_location" "snc"
}

clean_trash_dir() {
  local trash_dir="$1"

  rm -rf "$trash_dir"
}

backup_lg_dir() {
  local tools_dir="$HOME/.zsh/tools"
  source "$tools_dir/drives"

  bk_lg
}

main() {
  backup_drive="$1"
  working_dir=`pwd`
  date_stamp=`date +'%Y-%m-%d'`
  zip_location="$backup_drive/Snc/$date_stamp.zip"
  sync_dir="$BNK"
  trash_dir="$sync_dir/snc/.trash"
  
  navigate_to_sync_dir "$sync_dir"
  try_delete_preexisting_zip "$zip_location"
  zip_snc_dir "$zip_location"
  clean_trash_dir "$trash_dir"
}

main "$@"

