#!/bin/bash

#----------------
# Name          : agile_ticket_create
# Description   : Creates a template for tracking details while developing an agile ticket
# Author        : E Fournier
# Dependencies  : bash
# Example Usage : ./agile_ticket_create 'ticket_sprint' 'ticket_id' 'ticket_title'
#----------------

get_story_contents() {
  local ticket_sprint="$1"
  local ticket_id="$2"
  local ticket_title="$3"

  local company_name="savvylabs"
  local ticket_url="https://${company_name}.atlassian.net/browse/${ticket_id}"

  local ticket_title_with_id="$ticket_id | $ticket_title"

cat << EOF
# [$ticket_sprint | $ticket_id | $ticket_title]($ticket_url)

## Title

- $ticket_title_with_id

## Overview

- TODO

## Acceptance Criteria

- TODO

## Details

### Link

#### Url

- $ticket_url

#### Url With Title

- [$ticket_title_with_id]($ticket_url)

### Sprint

- $ticket_sprint

### Parent

- []()

### Points

- 

## Git

### Branch

- $ticket_id

### Commits

#### TODO

### Pull Request

#### Date

-

#### Url

-

#### Title

- $ticket_title_with_id

#### Comment

\`\`\`text
## Ticket

- [$ticket_id]($ticket_url)

## Changes

- 

\`\`\`

## Communication

### Messages | Slack | \`#\`

#### E | TODO

## Code

### TODO

## Notes

### TODO

## Loom

### Date

- TODO

### Title

- $ticket_title_with_id

### Link

#### Url

- 

#### Url With Title

- [$ticket_title_with_id]()

EOF
}

format_file_name() {
  local ticket_sprint="$1"
  local ticket_id="$2"
  local ticket_title="$3"

  local ticket_title_camel_case="${ticket_title// /}"
  local ticket_title_camel_case="${ticket_title_camel_case//And/+}"
  local ticket_title_camel_case="${ticket_title_camel_case//-/}"
  local ticket_title_camel_case="${ticket_title_camel_case//_/}"
  local ticket_title_camel_case="${ticket_title_camel_case//\>/_}"
  local ticket_title_camel_case="${ticket_title_camel_case//\|/_}"
  local ticket_title_camel_case="${ticket_title_camel_case//\//+}"

  local file_name_formatted="${ticket_sprint}_${ticket_id}_${ticket_title_camel_case}"

  echo "$file_name_formatted"
}

main() {
  local ticket_sprint="$1"
  local ticket_id="$2"
  local ticket_title="$3"

  local dir="$(pwd)"

  if [[ -z "$ticket_sprint" || -z "$ticket_id" || -z "$ticket_title" ]]; then
    echo "USAGE: agile_ticket_create 'ticket_sprint' 'ticket_id' 'ticket_title'"
    exit
  fi

  local file_name_formatted=`format_file_name "$ticket_sprint" "$ticket_id" "$ticket_title"`

  mkdir -p "${dir}/${file_name_formatted}"

  local ticket_file="${dir}/${file_name_formatted}/${file_name_formatted}.md"
  touch "$ticket_file"

  get_story_contents "$ticket_sprint" "$ticket_id" "$ticket_title" >> "$ticket_file"
}

main "$@"

