#!/bin/zsh

#----------------
# Name          : drives
# Description   : Aliases for drive operations
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Configuration
uuid_bnk="316fb91f-e238-4dce-b610-f7dfe74d8eec"
uuid_extA="082f97de-0589-46f9-99d3-850791eddfb3"
uuid_extB="8270e3db-a812-476c-b2bc-ef2bdb50e9e8"
uuid_extC="b790dcd2-3998-4f51-9365-397149e38f97"
uuid_extCM="034f2d78-cf47-4128-8564-1e418facbc39"
uuid_bkA="9ecb85bd-62f3-4f24-9801-8b3c2839903d"
uuid_bkB="d416cfe4-9b86-42da-9c33-4b3814a164de"
uuid_bkC="e6210770-ba18-4162-9be5-cbc647e229ce"
uuid_md="557302aa-ac1b-4cff-b7f0-3f8cf4db290b"

## Mountpoints

### /mnt/bnk

#### Base
export BNK="$BNK"

#### Mount
alias m_bnk=". $USCRIPTS/mount_uuid_veracrypt $uuid_bnk $BNK 33"

#### Unmount
alias um_bnk=". $USCRIPTS/umount_uuid_veracrypt $uuid_bnk"

### /mnt/extA

#### Base
export EXTA="/mnt/extA"

#### Mount
alias m_extA="$USCRIPTS/mount_uuid_veracrypt $uuid_extA $EXTA 8"

#### Unmount
alias um_extA="$USCRIPTS/umount_uuid_veracrypt $uuid_extA"

### /mnt/extB

#### Base
export EXTB="/mnt/extB"

#### Mount
alias m_extB=". $USCRIPTS/mount_uuid_veracrypt $uuid_extB $EXTB 12"

#### Unmount
alias um_extB=". $USCRIPTS/umount_uuid_veracrypt $uuid_extB"

### /mnt/extC

#### Base
export EXTC="/mnt/extC"

#### Mount
alias m_extC=". $USCRIPTS/mount_uuid_veracrypt $uuid_extC $EXTC 16"

#### Unmount
alias um_extC=". $USCRIPTS/umount_uuid_veracrypt $uuid_extC"

### /mnt/extC_Media

#### Base
export EXTCM="/mnt/extCM"

#### Mount
alias m_extCM=". $USCRIPTS/mount_uuid_veracrypt $uuid_extCM $EXTCM 17"

#### Unmount
alias um_extCM=". $USCRIPTS/umount_uuid_veracrypt $uuid_extCM"

### /mnt/bkA

#### Base
export BKA="/mnt/bkA"

#### Mount
alias m_bkA=". $USCRIPTS/mount_uuid $uuid_bkA $BKA"

#### Unmount
alias um_bkA=". $USCRIPTS/umount_uuid $uuid_bkA"

### /mnt/bkB

#### Base
export BKB="/mnt/bkB"

#### Mount
alias m_bkB=". $USCRIPTS/mount_uuid $uuid_bkB $BKB"

#### Unmount
alias um_bkB=". $USCRIPTS/umount_uuid $uuid_bkB"

### /mnt/bkC

#### Base
export BKC="/mnt/bkC"

#### Mount
alias m_bkC=". $USCRIPTS/mount_uuid $uuid_bkC $BKC"

#### Umount
alias um_bkC=". $USCRIPTS/umount_uuid $uuid_bkC"

### /mnt/md

#### Base
export MD="/mnt/md"

#### Mount
alias m_md=". $USCRIPTS/mount_uuid_veracrypt $uuid_md $MD 16"

#### Unmount
alias um_md=". $USCRIPTS/umount_uuid_veracrypt $uuid_md"

### Veracrypt

#### Mount Container Read Only
m_v_ro() { veracrypt -m ro "$1" "$2" }

#### Dismount Container
um_v() { veracrypt -d "$1" }

## Backups

### Create a zip backup of snc directory
alias bk_snc=". $USCRIPTS/backup_snc $EXTA"

### Create a zip backup of lg directory
alias bk_lg=". $USCRIPTS/backup_lg $EXTA"

### Backup extA to extB
alias bk_extAB=". $USCRIPTS/backup_dir $EXTA $EXTB"

### Backup extA to extB
alias bk_extBA=". $USCRIPTS/backup_dir $EXTB $EXTA"

### Backup extA to extC
alias bk_extAC=". $USCRIPTS/backup_dir $EXTA $EXTC Media/\*\*"

### Backup extA to extC
alias bk_extACM=". $USCRIPTS/backup_dir $EXTA/Media $EXTCM/Media"

### Backup extB to extC
alias bk_extBC=". $USCRIPTS/backup_dir $EXTB $EXTC /Media/**"

### Backup extA to MD
alias bk_extAMD=". $USCRIPTS/backup_dir $EXTA/Media $MD"

### Backup extB to MD
alias bk_extBMD=". $USCRIPTS/backup_dir $EXTB/Media $MD"

### Backup bkA to bkB
alias bk_bkAB=". $USCRIPTS/backup_dir $BKA $BKB"

### Backup bkA to bkB
alias bk_bkBA=". $USCRIPTS/backup_dir $BKB $BKA"

### Backup bkA to bkC
alias bk_bkAC=". $USCRIPTS/backup_dir $BKA $BKC"

### Backup bkB to bkC
alias bk_bkBC=". $USCRIPTS/backup_dir $BKB $BKC"

## Externals

### Rc record directory
export RCRC="$RC/RECORD"

### Dynamically exports external drive locations
export_ext_by_drive_letter() {
  local letter="$1"
  local base="$2"

  local this_year=`date +"%Y"`
  
  #### External base directory
  export ${letter}BASE="$base"

  #### Annual base directory
  export ${letter}ANN="$base/Annual"

  #### Annual directory for the current year
  export ${letter}YR="$base/Annual/$this_year"

  #### Lg base directory
  local lg="$base/Lg"
  export ${letter}LG="$lg"

  #### Lg audio directory
  export ${letter}ALG="$lg/Audio"

  #### Projects base directory
  local projects="$base/Projects"
  export ${letter}PROJ="$projects"

  #### Family projects directory
  export ${letter}FAM="$projects/FamilyMedia"

  #### Digitization projects directory
  export ${letter}DIG="$projects/Digitization"

  #### LeCoursville directory
  export ${letter}LEC="$projects/LeCoursville"
}

### Dynamically exports external media drive locations
export_media_by_drive_letter() {
  local letter="$1"
  local base="$2"

  #### Media base directory
  local media="$base/Media"
  export ${letter}MED="$media"
  
  #### Audio directory
  export ${letter}AU="$media/Audio"

  #### Video directory
  local video="$media/Video"
  export ${letter}VID="$video"

  #### Movies directory
  export ${letter}MOV="$video/Movies"

  #### TV directory
  export ${letter}TV="$video/TV"
}

### Exports variables for external drives
assign_drive_letters() {
  export_ext_by_drive_letter "A" "$EXTA"
  export_ext_by_drive_letter "B" "$EXTB"
  export_ext_by_drive_letter "C" "$EXTC"

  export_media_by_drive_letter "A" "$EXTA"
  export_media_by_drive_letter "B" "$EXTB"
  export_media_by_drive_letter "C" "$EXTC"
  export_media_by_drive_letter "M" "$MD"
}

assign_drive_letters

