#!/bin/zsh

#----------------
# Name          : linux_common
# Description   : Common shell-environment configuration for Linux systems
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### User home directory
export UHOME="$HOME"

### Hosts file
export HOSTS="/etc/hosts"

## Directories

### Sb mount point
export SB="$BNK/sbfs"

## Sources

### Drives
source "$ZALIAS/drives"

### Externals
source "$ZALIAS/externals"

### Sb
source "$ZALIAS/sb"

### Snc
source "$ZALIAS/snc"

### Tools
source "$ZALIAS/tools"

### Tmux
source "$ZALIAS/tmux"

## GUI Launchers

### Explore
explore() { nautilus "$1"; }

### Spreadsheet
spreadsheet() { libreoffice "$1"; }

### Word Processing
word() { libreoffice "$1"; }

### Presentation
presentation() { libreoffice "$1"; }

### Markdown
markdown() { chromium "$1"; }

### PDF
pdf() { evince "$1"; }

