#!/bin/zsh

#----------------
# Name          : linux_lubuntu_fmedia
# Description   : Shell-environment configuration for FMedia build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory
export BNK="$HOME/bnk"

### Start directory
export START="$HOME"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux Common
source "$ZENV/linux_common"

## Boot

### Tasks
run_boot_tasks() {
  export SYS_NAME="lubuntu_fmedia"
  $SCRIPTS/connect_vpn_persistently "Calypso" 60 &
  $SCRIPTS/connect_vnc_persistently 60 &
  $SCRIPTS/pulseaudio_set_default_sink "alsa.name" "HDMI" &

  xfce4-power-manager
  setxkbmap -option caps:escape
  delay_for_ui 2
  xdotool key Escape  

  gnome-terminal --window --maximize &
  kodi -fs &
}

