#!/bin/bash

#----------------
# Name          : boot_tasks
# Description   : Run boot-time tasks depending on the executing machine
# Author        : E Fournier
# Dependencies  : pkexec, dmidecode, kodi
# Example Usage : ./boot laptop
#----------------

shopt -s expand_aliases

delay_for_ui() {
  local delay_time=$1

  [[ -z $delay_time ]] && local delay_time=1

  sleep "$delay_time"
}

start_unison_snc() {
  local watch_script="$SCRIPTS/watch_for_change"

  [[ -z `pgrep inotifywait` && -f "$watch_script" ]] \
    && nohup "$watch_script" "$SNC" "$ZSCRIPTS/uni" >/dev/null 2>&1&
}

main() {
  local env_name="$(head -n 1 ~/.env_name)"

  . "$HOME/.zsh/env/common"
  . "$HOME/.zsh/alias/drives"
  . "$ZENV/$env_name"

  delay_for_ui 0.5

  run_boot_tasks
}

main "$@"

