#!/bin/bash

#----------------
# Name          : lg_open
# Description   : Opens contents of `lg` container in Vim
# Author        : E Fournier
# Dependencies  : vim
# Example Usage : ./lg_open
#----------------

main() {
  local year=`date +"%Y"`
  local last_year=$((year - 1))
  local all_files=`ls | tr '\n' ' '`

  echo -n "Password: "
  read -s password

  cd "$SNC/Lg"

  vim --cmd "set key=$password" \
    -o *.md \
    -c "source $ZSCRIPTS/lg_open.vim"
}

main "$@"

