#!/bin/bash

#----------------
# Name          : rc_mount
# Description   : Mounts rc drive by presumed UUIDs
# Author        : E Fournier
# Dependencies  : bash, readlink
# Example Usage : ./rc_mount
#----------------

is_uuid_attached() {
  local uuid="$1" 

  local readlink_response=`readlink "/dev/disk/by-uuid/$uuid"`

  [[ -z "$readlink_response" ]] \
    && echo false \
    || echo true
}

main() {
 local uuid_new="EC95-4FBB"
 local uuid_old="0000-006F"
 local uuid_alt="D68B-C6E5"
 local uuid_bank="9C33-6BBD"
  
  local is_uuid_new_attached=`is_uuid_attached $uuid_new`
  local is_uuid_old_attached=`is_uuid_attached $uuid_old`
  local is_uuid_alt_attached=`is_uuid_attached $uuid_alt`
  local is_uuid_bank_attached=`is_uuid_attached $uuid_bank`

  if [[ "$is_uuid_new_attached" == true ]]; then
    mount "/dev/disk/by-uuid/$uuid_new"
  elif [[ "$is_uuid_old_attached" == true ]]; then
    mount "/dev/disk/by-uuid/$uuid_old"
  elif [[ "$is_uuid_alt_attached" == true ]]; then
    mount "/dev/disk/by-uuid/$uuid_alt"
  elif [[ "$is_uuid_bank_attached" == true ]]; then
    mount "/dev/disk/by-uuid/$uuid_bank"
  else
    echo "ERROR: No rc drives found connected."
  fi
}

main "$@"

