#!/bin/bash

main() {
  local username="$1" 
  local address="$2"

  if [[ -z "$username" ]]; then
    echo "ERROR > Must supply username as 1st argument."
    exit
  fi

  if [[ -z "$address" ]]; then
    echo "ERROR > Must supply address as 2nd argument."
    exit
  fi

  rsync -au --progress "${username}@${address}:/home/${username}/bnk/rc/_processed" "$BNK/rc/" 
}

main "$@"

