#!/bin/bash

#----------------
# Name          : unison_start
# Description   : Starts the unison sync process
# Author        : E Fournier
# Dependencies  : nohup
# Example Usage : ./unison_start
#----------------

main() {
  local mode="$1"

  if ! command -v unison &> /dev/null; then
    echo "ERROR: Unison is not installed"
    exit
  fi
  
  local sync_file_location="$ZSCRIPTS/unison_sync"
  local server_domain="$lb_server_domain"
  local user="$lb_username"
  local server_bin_dir="/usr/bin"
  local local_sync_dir="$SNC"
  local server_sync_dir="/home/${user}/bnk/snc"
  local local_lg_dir="$SLG"
  local server_lg_dir="/home/${user}/bnk/snc/Lg"

  if [[ "$mode" == "watch" ]]; then
    nohup "$sync_file_location" "$server_domain" "$user" "$local_sync_dir" "$server_sync_dir" "$server_bin_dir" "watch" >/dev/null 2>&1&
  elif [[ "$mode" == "single_dir" && ! -z "$dir" ]]; then
    local snc_dir="$SNC/$dir"
    if [[ -d "$snc_dir" ]]; then
      "$sync_file_location" "$server_domain" "$user" "$local_lg_dir" "$server_lg_dir" "$server_bin_dir" "$snc_dir"
    else 
      echo "ERROR: Must a preexisting SNC directory to unison_start." >&2
      echo "Directory $snc_dir not found" >&2
    fi
  elif [[ "$mode" == "all" ]]; then
    "$sync_file_location" "$server_domain" "$user" "$local_lg_dir" "$server_lg_dir" "$server_bin_dir" "$dir"
  else
    echo "ERROR: Must provide valid arguments to unison_start" >&2
  fi
}

main "$@"
