#!/bin/bash

#----------------
# Name          : unison_start
# Description   : Starts the unison sync process
# Author        : E Fournier
# Dependencies  : nohup
# Example Usage : ./unison_start
#----------------

source "$HOME/.zsh/env/common"

main() {
  local mode="$1"

  if ! command -v unison &> /dev/null; then
    echo "ERROR: Unison is not installed"
    exit
  fi
  
  local sync_file_location="$ZSCRIPTS/unison_sync"
  local server_domain="$lb_server_domain"
  local user="$lb_username"
  local local_sync_dir="$SNC"
  local server_sync_dir="/home/${user}/bnk/snc"
  local server_bin_dir="/usr/bin"

  if [[ "$mode" == "watch" ]]; then
    nohup "$sync_file_location" "$server_domain" "$user" "$local_sync_dir" "$server_sync_dir" "$server_bin_dir" "watch" >/dev/null 2>&1&
  else
    "$sync_file_location" "$server_domain" "$user" "$local_sync_dir" "$server_sync_dir" "$server_bin_dir"
  fi
}

main "$@"

