#!/bin/bash

#----------------
# Name          : unison_sync
# Description   : Syncs local directory to remote using Unison
# Author        : E Fournier
# Dependencies  : unison, inotifywait, pgrep
# Example Usage : ./unison_sync
#----------------

#source "$HOME/.zsh/env/common"

validate_args() {
  local server="$1"
  local user="$2"
  local local_dir="$3"
  local remote_dir="$4"
  local remote_bin_dir="$5"

  if [[ \
       -z "$server" \
    || -z "$user" \
    || -z "$local_dir" \
    || -z "$remote_dir" \
    || -z "$remote_bin_dir" \
  ]]; then
    echo "ERROR: Arguments not supplied correctly"
    echo "USAGE: $ sync_unison $server $user $local_dir $remote_dir $remote_bin_dir"
    exit 1
  fi
}

should_start_sync_watcher() {
  [[ "$SYNC_ENABLED" == "true" && -z `pgrep inotifywait` ]] \
    && echo "true" \
    || echo "false"
}

watch_for_change() {
  local dir_to_watch="$1"

  inotifywait --recursive \
    --event modify,move,create,delete \
    $dir_to_watch
}

run_unison_command() {
  local server="$1"
  local user="$2"
  local local_dir="$3"
  local remote_dir="$4"
  local remote_bin_dir="$5"

  local log_dir="$HOME/.unison/logs"
  local log_file_name="unison.log"
  local log_file_path="$log_dir/$log_file_name"

  unison \
    -batch -force newer -perms 0 \
    -logfile "$log_file_path" \
    -backup 'Name *' \
    -backupprefix '' -backupsuffix '_$VERSION'"_$(date +%y%m%d%H%M%S)" \
    -sshargs '-o PasswordAuthentication=no' \
    -servercmd "$remote_bin_dir/unison" \
      "$local_dir" \
      "ssh://$user@$server/$remote_dir"
}

start_sync_watcher() {
  local server="$1"
  local user="$2"
  local local_dir="$3"
  local remote_dir="$4"
  local remote_bin_dir="$5"

  local log_dir="$HOME/.unison/logs"
  local log_file_name="unison.log"
  local log_file_path="$log_dir/$log_file_name"

  mkdir -p "$log_dir"

  while watch_for_change "$local_dir"; do
    run_unison_command "$server" "$user" "$local_dir" "$remote_dir" "$remote_bin_dir"
  done
}

main() {
  local server="$1"
  local user="$2"
  local local_dir="$3"
  local remote_dir="$4"
  local remote_bin_dir="$5"
  local mode="$6"

  validate_args "$server" "$user" "$local_dir" "$remote_dir" "$remote_bin_dir" 
  if [[ "$mode" == "watch" && `should_start_sync_watcher` = "true" ]]; then
      start_sync_watcher "$server" "$user" "$local_dir" "$remote_dir" "$remote_bin_dir"

  else
    run_unison_command "$server" "$user" "$local_dir" "$remote_dir" "$remote_bin_dir"

  fi
}

main "$@"

