#!/bin/bash

#----------------
# Name          : yt_audio
# Description   : Downloads a YouTube video as an audio file
# Author        : E Fournier
# Dependencies  : yt-dlp
# Example Usage : ./yt_audio
#----------------

main() {
  local download_url="$1"

  yt-dlp -f 'ba' -x --audio-format mp3 "$download_url"
}

main "$@"

