#!/bin/bash

#----------------
# Name          : lg_mount
# Description   : Mounts `lg` container
# Author        : E Fournier
# Dependencies  : veracrypt
# Example Usage : ./lg_mount
#----------------

main() {
  local parent_dir="$SNC"
  local file_name="$parent_dir/Lg.vc"
  local mount_point="$parent_dir/Lg"

  [[ ! -n "$(ls -A $SLG)" ]] && \
    veracrypt -t --pim=0 --keyfiles="" --protect-hidden=no "$file_name" "$mount_point"

  cd "$SLG"
}

main "$@"

