#!/bin/bash

#----------------
# Name          : backup_lg
# Description   : Backup up lg directory
# Author        : E Fournier
# Dependencies  : zip
# Example Usage : ./backup_lg /mnt/extA/lg/
#----------------

navigate_to_log_dir() {
  local log_dir="$1"

  cd "$log_dir"
}

navigate_to_starting_dir() {
  local working_dir="$1"

  cd "$working_dir"
}

delete_preexisting_zip() {
  local zip_file="$1"

  rm -rf "$zip_file"
}

zip_dir() {
  local zip_dir="$1"
  local zip_file="$2"

  local log_dir_name="Lg"

  zip -r "$zip_dir/$zip_file" "$log_dir_name"
}

main() {
  local backup_drive="$1"

  local log_dir="/mnt/bnk/snc"
  local working_dir=`pwd`
  local date_stamp=`date +'%Y-%m-%d'`
  local zip_dir="/mnt/$backup_drive/Lg/Backups"
  local zip_file="$date_stamp.zip"
  
  navigate_to_log_dir "$log_dir"
  delete_preexisting_zip "$zip_file"
  zip_dir "$zip_dir" "$log_dir"
  navigate_to_starting_dir "$working_dir"
}

main "$@"

