#!/bin/bash

#----------------
# Name          : boot_tasks
# Description   : Run boot-time tasks depending on the executing machine
# Author        : E Fournier
# Dependencies  : pkexec, dmidecode, kodi
# Example Usage : ./boot laptop
#----------------

alias_dir="$HOME/.zsh/alias"
shopt -s expand_aliases
source "$HOME/.zsh/env/env.zsh"
source "$alias_dir/drives.zsh"

is_validate_machine_type() {
  local machine_type="$1"

  [[ "$machine_type" != "laptop" && "$machine_type" != "media" ]] \
    && echo "false" \
    || echo "true"
}

delay_to_prevent_ui_bugs() {
  local delay_time=0.5

  sleep "$delay_time"
}

start_unison_snc() {
  local watch_script="$HSCRIPTS/watch_for_change"

  [[ -z `pgrep inotifywait` && -f "$watch_script" ]] \
    && nohup "$watch_script" "$SNC" "$ZSCRIPTS/uni" >/dev/null 2>&1&
}

run_laptop_tasks() {
  touchscreen_id="SYNA2393:00 06CB:19AC"

  xinput disable "$touchscreen_id"
  m_bnk
  start_unison_snc

  gnome-terminal --window --maximize
}

run_media_tasks() {
  m_md
  kodi -fs &
}

main() {
  local machine_type="$1"

  local machine_is_valid=`is_validate_machine_type "$machine_type"`
  if [[ "$machine_is_valid" == "false" ]]; then
    echo "ERROR: Must supply valid a valid machine type"
    exit 1
  fi

  delay_to_prevent_ui_bugs
  
  [[ "$machine_type" == "laptop" ]] && run_laptop_tasks

  [[ "$machine_type" == "media" ]]  && run_media_tasks
}

main "$@"

