#!/bin/bash

#----------------
# Name          : connect_vnc_persistently
# Description   : Continuously attempts to connect a TigerVNC 
# Author        : E Fournier
# Dependencies  : x0vncserver, nohup
# Example Usage : ./connect_vnc_persistently 60
#----------------

main() {
  local timeout_seconds=$1

  [[ -z "$timeout" ]] && local timeout_seconds=60

  while true; do
    [[ -z `pgrep x0vncserver` ]] \
      && nohup x0vncserver -PasswordFile "$HOME/.vnc/passwd"

    sleep $timeout_seconds
  done
}

main "$@"

