#!/bin/bash

#----------------
# Name          : connect_audio_persistently
# Description   : Continuously attempts to resolve PulseAudio issues pertaining to connections to the wrong sink
# Author        : E Fournier
# Dependencies  : 
# Example Usage : ./connect_audio_persistently "alsa.name" "HDMI" 60
#----------------

main() {
  local property_name="$1"
  local target_pattern="$2"
  local timeout_seconds=$3

  [[ -z "$timeout" ]] && local timeout_seconds=60

  while true; do
    $USCRIPTS/pulseaudio_set_default_sink "$property_name" "$target_pattern" &

    sleep $timeout_seconds
  done
}

main "$@"

