#!/bin/bash

main() {
  for (( i = 0; i <= 9; i++ )); do
    local command="gsettings set org.gnome.shell.keybindings switch-to-application-$i \"['<Super>$i']\""

    echo "SETTING > $command"

    eval "$command"
  done
}

main "$@"

