#!/bin/bash

#----------------
# Name          : rc_remote_audio_recieve
# Description   : Starts recording process on call to server
# Author        : E Fournier
# Dependencies  : ffmpeg
# Example Usage : ./rc_remote_audio_recieve "duration" "target_dir" "rc_device_name"
#----------------

output_verbose_details() {
  local duration="$1"
  local target_dir="$2"
  local rc_device_name_left="$3"
  local rc_device_card_left="$4"
  local rc_device_address_left="$5"
  local rc_device_name_right="$6"
  local rc_device_card_right="$7"
  local rc_device_address_right="$8"
  
  echo
  echo "--------------------"
  echo "RECORDING"
  echo "--------------------"
  echo "DURATION             : $duration"
  echo "TARGET DIR           : $target_dir"
  echo "LEFT DEVICE NAME     : $rc_device_name_left"
  echo "LEFT DEVICE CARD     : $rc_device_card_left"
  echo "LEFT DEVICE ADDRESS  : $rc_device_address_left"
  echo "RIGHT DEVICE NAME    : $rc_device_name_right"
  echo "RIGHT DEVICE CARD    : $rc_device_card_right"
  echo "RIGHT DEVICE ADDRESS : $rc_device_address_right"
  echo "--------------------"
  echo
}

extract_between_brackets() {
  local line="$1"

  echo `echo "$line" | cut -d "[" -f2 | cut -d "]" -f1  | xargs`
}

get_device_card() {
  local device_name="$1"

  while read line; do
    if [[ "$line" =~ "$device_name" ]] && [[ "$line" =~ ']:' ]]; then
      local device_card=`extract_between_brackets "$line"`
    fi
  done < <(cat /proc/asound/cards)
  
  if [[ -z "$device_card" ]]; then
    echo "ERROR > Failed to find a card for device: $device_name."
    exit
  fi

  echo "$device_card"
}

main() {
  local duration="$1"
  local target_dir="$2"
  local rc_device_name_left="$3"
  local rc_device_name_right="$4"
  
  local rc_device_card_left=`get_device_card "$rc_device_name_left"`
  local rc_device_address_left="plughw:CARD=$rc_device_card_left,DEV=0"

  if [[ ! -z "$rc_device_name_right" ]]; then
    local rc_device_card_right=`get_device_card "$rc_device_name_right"`
    local rc_device_address_right="plughw:CARD=$rc_device_card_right,DEV=0"
  fi

  output_verbose_details "$duration" "$target_dir" "$rc_device_name_left" "$rc_device_card_left" "$rc_device_address_left" "$rc_device_name_right" "$rc_device_card_right" "$rc_device_address_right" 

  ~/.scripts/rc_record "$duration" "$target_dir" "$rc_device_address_left" "$rc_device_address_right"
}

main "$@"

