#!/bin/bash

#----------------
# Name          : system_update
# Description   : Runs a series of update tasks to automate routine maintenance of Ubuntu systems
# Author        : E Fournier
# Dependencies  : apt, snap
# Example Usage : ./system_update
#----------------

print_header() {
  local header_title="$1"
  echo
  echo "-------------------------------"
  echo "# $header_title"
  echo "-------------------------------"
}

main() {
  # Prompt for admin password, in necessary
  sudo printf ""
  
  print_header "APT UPDATE"
  sudo apt -y update

  print_header "APT UPGRADE"
  sudo apt -y upgrade

  print_header "APT INSTALL"
  sudo apt -y install

  print_header "APT AUTOREMOVE"
  sudo apt -y autoremove

  print_header "APT AUTOCLEAN"
  sudo apt -y autoclean

  print_header "APT CLEAN"
  sudo apt -y clean

  print_header "APT PURGE"
  sudo apt -y purge

  print_header "APT REMOVE"
  sudo apt -y remove

  print_header "SNAP REFRESH"
  sudo snap refresh

  print_header "CLEAN WITH BLEACHBIT"
  $USCRIPTS/clean_with_bleachbit

  print_header "CLEAN WITH BLEACHBIT AS ADMIN"
  sudo $USCRIPTS/clean_with_bleachbit

  # print_header "CLEAN CHROME CACHE STORAGE"
  # setopt localoptions rmstarsilent
  # rm -rv ~/.config/google-chrome/Profile\ */Service\ Worker/CacheStorage/*

  print_header "USAGE > DISK"
  df -h

  print_header "USAGE > BOOT PARTITION"
  df -h /boot
}

main "$@"

