#!/bin/bash

main() {
  local interval_in_seconds=$1

  [[ -z $interval_in_seconds ]] && local interval_in_seconds=60

  while true; do
    local timestamp=`date +'%y%m%d-%H%M%S'`

    scrot "${timestamp}.png" -e 'echo $n'

    sleep $interval_in_seconds
  done
}

main "$@"

