#!/bin/bash

get_timestamp_using_ffmpeg() {
  local file_name="$1"

  ffmpeg -i "$file_name" 2>&1 \
    | grep Duration \
    | cut -d " " -f 4 \
    | sed "s/,//" \
    | sed "s/\..*//"
}

get_timestamp_using_ffprobe() {
  local file_name="$1"

  ffprobe -v error \
    -show_entries format=duration \
    -of default=noprint_wrappers=1:nokey=1 \
    -sexagesimal \
    "$file_name"
}

get_duration_of_each_file_in_dir() {
  local dir="$1"

  for file in $dir/*; do
    local duration=`get_timestamp_using_ffmpeg "$file"`
    echo "$duration => $file" >&2
  done
}

get_dir_duration_using_ffmpeg() {
  local dir="$1"

  get_duration_of_each_file_in_dir "$dir"

  local dir_duration_in_seconds=`find . -maxdepth 1 -iname '*.mp3' -exec ffprobe -v quiet -of csv=p=0 -show_entries format=duration {} \; | paste -sd+ -| bc`

  local dir_duration_timestamp=`date -u -d @${dir_duration_in_seconds} +"%T"`

  echo "$dir_duration_timestamp"
}

main() {
  local file_name="$1"

  if [[ -f "$file_name" ]]; then
    local duration=`get_timestamp_using_ffmpeg "$file_name"`
    echo "File Duration: $duration"
    exit
  elif [[ -d "$file_name" ]]; then
    local duration=`get_dir_duration_using_ffmpeg "$file_name"`
    echo "Directory Duration: $duration"
    exit
  else
    echo "ERROR: Inputted file or directory could not be found."
  fi
}

main "$@"

