#!/bin/bash

get_timestamp_using_ffmpeg() {
  local file_name="$1"

  ffmpeg -i "$file_name" 2>&1 \
    | grep Duration \
    | cut -d " " -f 4 \
    | sed "s/,//" \
    | sed "s/\..*//"
}

get_timestamp_using_ffprobe() {
  local file_name="$1"

  ffprobe -v error \
    -show_entries format=duration \
    -of default=noprint_wrappers=1:nokey=1 \
    -sexagesimal \
    "$file_name"
}

main() {
  local file_name="$1"

  get_timestamp_using_ffmpeg "$file_name"
}

main "$@"

