#!/bin/bash

source "$HOME/.zsh/env/env.zsh"

watch_for_change() {
  local dir_to_watch="$1"

  [[ -z "$SYNC_TIMEOUT" ]] && SYNC_TIMEOUT="3600"

  inotifywait --recursive \
    --event modify,move,create,delete \
    --timeout $SYNC_TIMEOUT \
    $dir_to_watch
}

main() {
  local dir_to_watch="$1"
  local script_to_run="$2"

  while watch_for_change $dir_to_watch; do
    bash "$script_to_run"
  done
}

main "$@"

