#!/bin/bash

#----------------
# Name          : website_download
# Description   : 
# Author        : E Fournier
# Dependencies  : wget
# Example Usage : ./website_download "www.linuxjournal.com" "/content/downloading-entire-web-site-wget"
#----------------

get_without_cookies() {
  local domain="$1"
  local full_path="$2"

  wget \
    --recursive \
    --page-requisites \
    --adjust-extension \
    --span-hosts \
    --convert-links \
    --restrict-file-names=windows \
    --domains "$domain" \
    --no-parent \
    "${full_path}"
}

get_with_cookies() {
  local domain="$1"
  local full_path="$2"
  local cookies_file="$3"

  wget \
    --recursive \
    --page-requisites \
    --adjust-extension \
    --span-hosts \
    --convert-links \
    --restrict-file-names=windows \
    --load-cookies "$cookies_file" \
    --domains "$domain" \
    --no-parent \
    "${full_path}"
}

main() {
  local domain="$1"
  local path="$2"
  local cookies_file="$3"

  local full_path="${domain}${path}"

  if [[ -z "$cookies_file" ]]; then
    get_without_cookies "$full_path" "$domain"
  else
    get_with_cookies "$full_path" "$domain" "$cookies_file"
  fi
}

main "$@"

