#!/bin/zsh

#----------------
# Name          : common
# Description   : Environment-specific configuration for ZSH
# Author        : E Fournier
# Dependencies  : zsh
#----------------
 
## Environment

### Zsh
 
#### Zsh root directory
export ZZSH="$HOME/.zsh"

#### Oh-My-Zsh directory
export ZOHMYZSH="$HOME/.oh-my-zsh"

#### Zsh alias directory
export ZALIAS="$ZZSH/alias"

#### Zsh plugins directory
export ZPLUGINS="$ZZSH/plugins"

#### Zsh alias directory
export ZENV="$ZZSH/env"

#### Zsh scripts directory
export ZSCRIPTS="$ZZSH/scripts"

#### Zsh cache directory
export ZSH_COMPDUMP="${HOME}/.cache/.zcompdump-${ZSH_VERSION}"

### Load environment-specific configuration
source "$ZENV/$ENV_NAME"

### Oh-My-Zsh

#### Shell theme
[[ -z $ZSH_THEME ]] && ZSH_THEME="avit"

#### Disable update prompts
DISABLE_AUTO_UPDATE=true

DISABLE_AUTO_TITLE=true

#### Load oh-my-zsh assets
ZSH="$ZOHMYZSH"
source "$ZSH/oh-my-zsh.sh"

#### Enable extension for syntax highlighting
source "$ZPLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

#### Set custom highlighting for the `ls` command
export LS_COLORS="di=31:tw=31:ow=31:fi=32:su=32:sg=32:ex=32:so=36:pi=36:bd=36:cd=36:ln=36:"

#### Use same highlighting for completion as for the `ls` command
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

## System

### Shell
export SHELL="zsh"

### Editor
export EDITOR="vim"

### Language
export LANG="en_US.UTF-8"

### Preserve natural sort order
export LC_COLLATE="C"

### The current year
export THIS_YEAR=`date +"%Y"`

## File System

### Home

#### Desktop
export UDESK="$UHOME/Desktop"

#### Desktop
export UDOWN="$UHOME/Downloads"

#### Documents
export UDOCS="$UHOME/Documents"

#### Documents
export UPICS="$UHOME/Pictures"

### SB

#### SB root directory
export SBROOT="/home/misigno"

### Bnk

#### Cs
export CS="$BNK/cs"

#### Hle
export HLE="$BNK/hle"

#### Snc
export SNC="$BNK/snc"

#### Scripts
export SCRIPTS="$HOME/.scripts"

#### Ensure relevant directories exist
mkdir -p "$BNK" "$SNC" "$CS" "$HLE"

### Vim

#### Vim root directory
export VVIM="$HOME/.vim"

#### Vim snippets directory
export VSNIPS="$VIM/snippets"

### Tmux

##### Tmux root directory
export TTMUX="$HOME/.tmux"

##### Tmux session directory
export TSESSIONS="$TTMUX/sessions"

##### Tmux scripts directory
export TSCRIPTS="$TTMUX/scripts"

### Git
git config --global diff.tool vimdiff
git config --global difftool.prompt false

## Display

### Prevent partial-line %
unsetopt PROMPT_SP

## Privacy

### History

#### Maximum history items in memory
HISTSIZE=1000

#### Do not persist history to file
SAVEHIST=0

#### Unset history file location
HISTFILE=""

## Tweaks

### Always list directory contents on change
chpwd() { ls }

## Tools

### Unison

#### Ensure unique host name per machine
export UNISONLOCALHOSTNAME=`cat /etc/machine-id`

#### Conditionally start the unison sync process
$SYNC_ENABLED && $ZSCRIPTS/unison_start watch

