#!/bin/zsh

#----------------
# Name          : common
# Description   : Common configuration for ZSH environments
# Author        : E Fournier
# Dependencies  : zsh
#----------------
 
## Environment

### Zsh
 
#### Zsh root directory
export ZZSH="$HOME/.zsh"

#### Oh-My-Zsh directory
export ZOHMYZSH="$HOME/.oh-my-zsh"

#### Zsh alias directory
export ZTOOLS="$ZZSH/tools"

#### Zsh plugins directory
export ZPLUGINS="$ZZSH/plugins"

#### Zsh environment directory
export ZENV="$ZZSH/env"

#### Zsh scripts directory
export ZSCRIPTS="$ZZSH/scripts"

#### Zsh cache directory
export ZSH_COMPDUMP="${HOME}/.cache/.zcompdump-${ZSH_VERSION}"

### Create env_id file
export ENV_ID="$($ZSCRIPTS/env_id_get)"

### Load environment-specific configuration
source "$ZENV/$ENV_NAME"

### Oh-My-Zsh

#### Shell theme
[[ -z $ZSH_THEME ]] && ZSH_THEME="avit"

#### Disable update prompts
DISABLE_AUTO_UPDATE=true

#### Hide user and host from auto titles
DISABLE_AUTO_TITLE=true

#### Set global variable
ZSH="$ZOHMYZSH"

#### Load oh-my-zsh assets
source "$ZSH/oh-my-zsh.sh"

#### Enable extension for syntax highlighting
source "$ZPLUGINS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

#### Set custom highlighting for the `ls` command
export LS_COLORS="di=31:tw=31:ow=31:fi=32:su=32:sg=32:ex=32:so=36:pi=36:bd=36:cd=36:ln=36:"

#### Use same highlighting for completion as for the `ls` command
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

## System

### Shell
export SHELL="zsh"

### Editor
export EDITOR="vim"

### Language
export LANG="en_US.UTF-8"

### Preserve natural sort order
export LC_COLLATE="C"

### The current year
export THIS_YEAR=`date +"%Y"`

## File System

### Home

#### Desktop
export UDESK="$UHOME/Desktop"

#### Desktop
export UDOWN="$UHOME/Downloads"

#### Documents
export UDOCS="$UHOME/Documents"

#### Documents
export UPICS="$UHOME/Pictures"

### SB

#### SB root directory
export SBROOT="/home/misigno"

### Bnk

#### Cs
export CS="$BNK/cs"

#### Hle
export HLE="$BNK/hle"

#### Snc
export SNC="$BNK/snc"

#### Scripts
export USCRIPTS="$HOME/.scripts"

#### Ensure relevant directories exist
mkdir -p "$BNK" "$SNC" "$CS" "$HLE" > /dev/null 2>&1

### Vim

#### Vim root directory
export VVIM="$HOME/.vim"

#### Vim snippets directory
export VSNIPS="$VIM/snippets"

### Tmux

##### Tmux root directory
export TTMUX="$HOME/.tmux"

##### Tmux session directory
export TSESSIONS="$TTMUX/sessions"

##### Tmux scripts directory
export TSCRIPTS="$TTMUX/scripts"

### Git

#### Diff tool

##### Use vim for diffing
git config --global diff.tool vimdiff

##### Disable the prompt before diffing
git config --global difftool.prompt false

## Display

### Prevent partial-line %
unsetopt PROMPT_SP

## Privacy

### History

#### Maximum history items in memory
HISTSIZE=1000

#### Do not persist history to file
SAVEHIST=0

#### Unset history file location
HISTFILE=""

## Tweaks

### Always list directory contents on change
chpwd() { ls }

## Tools

### Unison

#### Ensure unique host name per machine
export UNISONLOCALHOSTNAME="$ENV_ID"

#### Conditionally start the unison sync process
$SYNC_ENABLED && $ZSCRIPTS/unison_start watch

### Sync with Unison
alias uni=". $ZSCRIPTS/unison_start"

## Overrides

### Location

#### Whereami
alias whereami="curl ipinfo.io"

### List

#### List Block Devices with UUIDs
alias lsuuid="lsblk -o NAME,FSTYPE,PARTLABEL,UUID,PARTUUID"

## Files

### Cleanup

#### List `._` Files
alias dotunderls="find . -name '._*' -print"

#### Delete `._` Files
alias dotunderrm="find . -name '._*' -delete -print"

### Dot Files

#### Copy from current directory to $HOME
alias dot_files_to_home="cp -r .tmux .tmux.conf .vim .vimrc .zsh .zshrc $HOME"

#### Copy from $HOME to current directory
alias dot_files_from_home="cp -rv ~/.tmux ~/.tmux.conf ~/.vim ~/.vimrc ~/.zsh ~/.zshrc ."

### Notes

#### Start session
alias notes=". $TSESSIONS/notes.session"

#### Kill session
alias notes!="tmux kill-session -t notes"

