#!/bin/zsh

#----------------
# Name          : fmedia_linux_lubuntu
# Description   : Shell-environment configuration for FMedia build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$HOME"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux Common

source "$ZENV/linux_common"

## Boot

### Tasks

run_boot_tasks() {
  export SYS_NAME="linux_lubuntu_fmedia"
  $ZSCRIPTS/sound/connect_persistently_audio_sink 60 "alsa.name" "HDMI" &
  $ZSCRIPTS/sound/connect_persistently_vnc 60 &
  $ZSCRIPTS/sound/connect_persistently_wifi 60 "FW-FamilyRoom" "FW-East" &
  #$ZSCRIPTS/sound/connect_persistently_vpn 60 "Calypso" &

  xfce4-power-manager &
  setxkbmap -option caps:escape &

  gnome-terminal --window --maximize &
  kodi -fs >/dev/null 2>&1 &
}

