#!/bin/zsh

#----------------
# Name          : linux_manjaro_general
# Description   : Shell-environment configuration for General build on Linux Manjaro
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Bnk directory
export BNK="$HOME/bnk"

### Start directory
export START="$BNK"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux common
source "$ZENV/linux_common"

