#!/bin/zsh

#----------------
# Name          : linux_lubuntu_fmedia
# Description   : Shell-environment configuration for FMedia build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory
export BNK="$HOME/bnk"

### Start directory
export START="$HOME"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux Common
source "$ZENV/linux_common"

start_service() {
  local service_name="$1"

  echo "Enabling Service: $service_name"

  systemctl start "${service_name}.service"
}

stop_service() {
  local service_name="$1"

  systemctl stop "${service_name}.service"
}

## Boot

### Tasks
run_boot_tasks() {
  export SYS_NAME="linux_lubuntu_fmedia"
  $USCRIPTS/connect_persistently_audio_sink 60 "alsa.name" "HDMI" &
  $USCRIPTS/connect_persistently_vnc 60 &
  $USCRIPTS/connect_persistently_wifi 60 "FW-FamilyRoom" "FW-East" &
  #$USCRIPTS/connect_persistently_vpn 60 "Calypso" &

  xfce4-power-manager &
  setxkbmap -option caps:escape &

  gnome-terminal --window --maximize &
  kodi -fs >/dev/null 2>&1 &
}

