#!/bin/zsh

#----------------
# Name          : linux_lubuntu_media
# Description   : Shell-environment configuration for Media build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory
export BNK="$HOME/bnk"

### Start directory
export START="$HOME"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux Common
source "$ZENV/linux_common"

## Boot

### Tasks
run_boot_tasks() {
  $USCRIPTS/connect_vpn_persistently "Calypso" 60 &
  $USCRIPTS/connect_vnc_persistently 60 &
  $USCRIPTS/pulseaudio_set_default_sink "alsa.name" "HDMI" &

  setxkbmap -option caps:escape
  pacmd set-default-sink alsa_output.platform-bcm2835_audio.stereo-fallback

  delay_for_ui 2
  xdotool key Escape  
  m_md

  gnome-terminal --window --maximize &
  kodi -fs &
}

