#!/bin/zsh

#----------------
# Name          : linux_lubuntu_fmedia
# Description   : Shell-environment configuration for FMedia build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory
export BNK="$HOME/bnk"

### Start directory
export START="$HOME"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux Common
source "$ZENV/linux_common"

## Boot

### Tasks
run_boot_tasks() {
  export SYS_NAME="linux_lubuntu_fmedia"
  $USCRIPTS/connect_audio_persistently "alsa.name" "HDMI" 6000 &
  $USCRIPTS/connect_vnc_persistently 60 &
  $USCRIPTS/connect_vpn_persistently "Calypso" 60 &
  $USCRIPTS/connect_wifi_persistently "FW-East" 60 &

  xfce4-power-manager
  setxkbmap -option caps:escape

  gnome-terminal --window --maximize &
  kodi -fs &
}

