#!/bin/zsh

#----------------
# Name          : primary_linux_ubuntu_gnome
# Description   : Shell-environment configuration for Primary build on Linux Ubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Bnk directory

export BNK="/mnt/bnk"

### Start directory

export START="$HOME"

export PATH="$HOME/.npm-global/bin:$PATH"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux common

source "$ZENV/common_linux"

[[ -d "$BNK/hle" ]] || m_bnk

## Boot

### Tasks

run_boot_tasks() {
  setxkbmap -option caps:escape &
  xfce4-terminal --window --maximize
}

