#!/bin/zsh

#----------------
# Name          : media_slideshow_linux_lubuntu
# Description   : Shell-environment configuration for Media-Slideshow build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$HOME"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux Common

source "$ZENV/linux_common"

## Boot

### Tasks

run_boot_tasks() {
  $USCRIPTS/pulseaudio_set_default_sink "alsa.name" "HDMI" &

  setxkbmap -option caps:escape
  pacmd set-default-sink alsa_output.platform-bcm2835_audio.stereo-fallback

  xdotool key Escape  

  gnome-terminal --window --maximize &
  kodi -fs >/dev/null 2>&1 &
}

