#!/bin/zsh

#----------------
# Name          : media_linux_manjaro_gnome
# Description   : Shell-environment configuration for Media build on Linux Manjaro
# Author        : E Fournier
# Dependencies  : zsh, xdotool, kodi, gnome, gnome-terminal
#----------------

## File System

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$HOME"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux Common

source "$ZENV/linux_common"

## Boot

### Tasks

run_boot_tasks() {
  $USCRIPTS/connect_vpn_persistently "Calypso" 60 &
  $USCRIPTS/connect_vnc_persistently 60 &
  $USCRIPTS/pulseaudio_set_default_sink "alsa.name" "HDMI" &

  setxkbmap -option caps:escape

  gsettings set org.gnome.desktop.screensaver lock-enabled false
  gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "suspend"
  gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 5400

  delay_for_ui 4
  xdotool key Escape  
  m_md

  gnome-terminal --window --maximize &
  kodi -fs >/dev/null 2>&1 &
}

