#!/bin/zsh

#----------------
# Name          : media_linux_ubuntu_lxde
# Description   : Shell-environment configuration for Media build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File System

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$HOME"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux Common

source "$ZENV/linux_common"

## Boot

### Tasks

run_boot_tasks() {
  export SYS_NAME="linux_lubuntu_media"
  $ZSCRIPTS/sound/connect_persistently_audio_sink 60 "alsa.name" "HDMI" &

  xfce4-power-manager &
  setxkbmap -option caps:escape &

  m_md

  gnome-terminal --window --maximize &
  kodi -fs >/dev/null 2>&1 &
}

