#!/bin/zsh

#----------------
# Name          : primary_linux_common
# Description   : Common configuration for Primary build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Files

### Bookmarks
alias bookmarks="vim $SDOCS/bck/bookmarks.md"

### Open Budget spreadsheet
alias budget="spreadsheet $SDOCS/Fin/Budget_${THIS_YEAR}.xls"

### Open financial tabs in Chrome
alias banking="$SDOCS/Fin/browser_tabs_banking"

### Open Amazon Fresh tabs in Chrome
alias fresh="$SDOCS/Hlt/browser_tabs_fresh"

### Open Weight spreadsheet
alias weight="spreadsheet $SDOCS/Hlt/Diet/Weight.xlsx"

### Open Jeopardy-download page in browser
alias jeopardy_episodes="$SDOCS/Gme/Scripts/jeopardy_episodes"

### Open Jeopardy spreadsheet
alias jeopardy_games="$SDOCS/Gme/Scripts/jeopardy_games"

### Open Chords markdown file
chords_file="$SDOCS/Mus/Chords.md"
alias chords="markdown $chords_file > /dev/null & vim $chords_file"

### Open music-practice spreadsheet
alias music_practice="libreoffice $SDOCS/Mus/Practice/Music_Practice.xlsx"

### Open Nautilus in a detached process nohup process
nnautilus() { nohup nautilus "$1" </dev/null >/dev/null 2>&1 &! }

## Lg

### Text

#### Mount Lg Container
alias m_lg="$USCRIPTS/m_lg"

### Audio

#### Run Audio-Lg Script
alias aud_lg="$USCRIPTS/audio_lg -i $RC/RECORD -o $EXTA/Lg/Audio"

## Browser

### Launch Tor
alias tor="GTK_THEME=Adwaita:light torbrowser-launcher"

### Torr
alias torr="$USCRIPTS/torr"

## Web

#### Command to open a URL in a fresh browser session
alias open_browser_url="google-chrome-stable --new-window"

### Material-Color-Picker Web Utility
alias material_colors="open_browser_url https://materialui.co/colors"

### Download YouTube Audio
yt_audio() { "$ZSCRIPTS/yt_audio" "$1"; }

source "$ZZSH/.secrets"

alias lb_ssh="ssh ${lb_username}@${lb_server_domain}"
alias lb_rc="$ZSCRIPTS/ssh_download ${lb_server_domain} ${lb_username}"

## SB

### SB root directory
export SBROOT="/home/${sb_username}"

### Connect to SSH Session
alias sbssh="ssh ${sb_username}@${sb_server_name}.${sb_server_domain}"

### VPN

#### Connect to VPN
alias sbvpn="nmcli con up id $sb_server_name"

#### Disconnect from VPN
alias sbvpn!="nmcli con down id $sb_server_name"

### Local Filesystem

#### Mount slot to local filesystem
alias sbfs=". $USCRIPTS/mount_sbfs $SBFS"

#### Unmount slot from local filesystem
alias sbfs!="fusermount -u $SBFS"

### Tmux

#### Start session
alias sb=". $TSESSIONS/sb.session"

#### Kill session
alias sb!="tmux kill-session -t sb"

