#!/bin/zsh

#----------------
# Name          : primary_linux_ubuntu_gnome
# Description   : Shell-environment configuration for Primary build on Linux Ubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Bnk directory
export BNK="/mnt/bnk"

### Start directory
export START="$BNK"

## Tools

### Sync

#### Enable unison
export SYNC_ENABLED=false

## Resources

### Linux common
source "$ZENV/common_linux"

### Primary common
source "$ZENV/primary_linux_common"

## External Devices

### Phones

#### Nexus

##### Phone ID
phone_id="SAMSUNG_SAMSUNG_Android_28c97b85383f7ece"

##### Mount
function m_phone() { gio mount "mtp://$phone_id"; }

##### Dismount
function m_phone!() { gio mount -u "mtp://$phone_id"; }

##### Access Files
function cd_phone() { cd "/run/user/1000/gvfs/mtp:host=$phone_id/Phone"; }

## Boot

### Tasks
run_boot_tasks() {
  gsettings set org.gnome.desktop.input-sources xkb-options "['caps:escape']"
  gsettings set org.gnome.desktop.screensaver lock-enabled true
  gsettings set org.gnome.desktop.media-handling automount false
  gsettings set org.gnome.desktop.media-handling automount-open false 

  PATH="$PATH:$HOME/.local/bin"

  m_bnk
  
  pactl unload-module module-switch-on-connect
  pactl load-module module-combine-sink
  pactl set-default-sink combined

  gnome-terminal --window --maximize
}

