#!/bin/zsh

#----------------
# Name          : primary_linux_root
# Description   : Shell-environment configuration for Primary build for Linux Root user
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Environment

### Override Oh-My-Zsh theme
ZSH_THEME="jonathan"

## File system

### Bnk directory
export BNK="/mnt/bnk"

### Start directory
export START="$BNK"

## Tools

### Sync

#### Enable unison
export AUTO_SNC_ENABLED=false

## Resources

### Linux common
source "$ZENV/linux_common"

