#!/bin/zsh

#----------------
# Name          : primary_macos_common
# Description   : Common configuration for Primary build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## App Openers

### Browser

browser_u() { open -na 'Firefox' --args --new-window "$1" }
browser_a() { open -na 'Google Chrome' --args --new-window "$1" }

### Spreadsheet

spreadsheet() { open -na 'LibreOffice' --args --calc $1 }

### DiskUtil

alias dlist="diskutil list"
alias dinfo="diskutil info"

### Download YouTube Audio

yt_audio() { "$ZSCRIPTS/download/yt_audio" "$1"; }

