#!/bin/zsh

#----------------
# Name          : primary_linux_common
# Description   : Common configuration for Primary build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Files

### Bookmarks
alias bookmarks="vim $SDOCS/bck/bookmarks.md"

### Open Budget spreadsheet
alias budget="spreadsheet $SDOCS/Fin/Budget_${THIS_YEAR}.xls"

### Open financial tabs in Chrome
alias banking="$SDOCS/Fin/browser_tabs_banking"

### Open Amazon Fresh tabs in Chrome
alias fresh="$SDOCS/Hlt/browser_tabs_fresh"

### Open Red Sox tabs in Chrome
alias redsox="$SDOCS/Gme/Scripts/browser_tabs_redsox"

### Open Weight spreadsheet
alias weight="spreadsheet $SDOCS/Hlt/Diet/Weight.xlsx"

### Open Jeopardy-download page in browser
alias jeopardy_episodes="$SDOCS/Gme/Scripts/jeopardy_episodes"

### Open Jeopardy spreadsheet
alias jeopardy_games="$SDOCS/Gme/Scripts/jeopardy_games"

### Open Chords markdown file
chords_file="$SDOCS/Mus/Chords.md"
alias chords="markdown $chords_file > /dev/null & vim $chords_file"

### Open music-practice spreadsheet
alias music_practice="libreoffice $SDOCS/Mus/Practice/Music_Practice.xlsx"

### Open Nautilus in a detached process nohup process
nnautilus() { nohup nautilus "$1" </dev/null >/dev/null 2>&1 &! }

## Browser

### Launch Tor
alias tor="GTK_THEME=Adwaita:light torbrowser-launcher"

### Torr
alias torr="$USCRIPTS/torr"

## Web

#### Command to open a URL in a fresh browser session
alias open_browser_url="google-chrome-stable --new-window"

### Material-Color-Picker Web Utility
alias material_colors="open_browser_url https://materialui.co/colors"

### Download YouTube Audio
yt_audio() { "$USCRIPTS/yt_audio" "$1"; }

source "$ZZSH/.secrets"

## SB

### SB root directory
export SBROOT="/home/${sb_username}"

## SSH Connections

### Connect to SB via SSH
alias ssh_sb="ssh ${sb_username}@${sb_server_name}.${sb_server_domain}"

### Connect to LB via SSH
alias ssh_lb="ssh ${lb_username}@${lb_server_domain}"

### Connect to MB via SSH
alias ssh_mb="ssh ${mb_username}@${mb_server_domain}"

## RC

### Download

#### Download RC from LB over SSH
alias rc_remote_download_lb="$USCRIPTS/rc_download $lb_username $lb_server_domain /mnt/bnk/rc"

#### Download RC from MB over SSH
alias rc_remote_download_mb="$USCRIPTS/rc_download $mb_username $mb_server_domain /mnt/bnk/rc"

#### Download RC from both LB and MB over SSH
rc_remote_download_all() { rc_remote_download_lb; rc_remote_download_mb }

### Clean

#### Clean RC directories from MB over SSH
alias rc_remote_clean_lb="$USCRIPTS/rc_clean $lb_username $lb_server_domain /home/misigno"

#### Download RC from MB over SSH
alias rc_remote_clean_mb="$USCRIPTS/rc_clean $mb_username $mb_server_domain /home/misigno"

#### Download RC from both LB and MB over SSH
rc_remote_clean_all() { rc_remote_clean_lb; rc_remote_clean_mb }

### Phone
alias rc_remote_phone="$USCRIPTS/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 08:00:00 /home/$lb_username/bnk/rc 'USB-Audio - USB Audio Device'"

### Microphone
alias rc_remote_mic="$USCRIPTS/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 08:00:00 /home/$lb_username/bnk/rc 'USB PnP Audio Device'"

### Zoom
alias rc_remote_zoom="$ZSCRIPTS/combined_audio_sink_enable; $USCRIPTS/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 08:00:00 /home/$lb_username/bnk/rc 'Creation' 'USB PnP Audio Device'"

### Thumbs

#### Base
export RC="/mnt/rc"

#### Mount
alias rc_thumb_mount="$ZSCRIPTS/rc_mount"

#### Unmount
alias rc_thumb_mount!="umount $RC"

#### List files
alias rc_thumb_list="ls -lh $RC/RECORD"

#### Remove WAV files
alias rc_thumb_clean="rm $RC/RECORD/*.WAV"

#### Convert Files
alias rc_thumb_process="$USCRIPTS/rc_thumb_process -i $RC/RECORD -o $EXTA/Lg/Audio"

### Bank

#### Mount
alias rc_bank_mount="$ZSCRIPTS/rc_mount"

#### Unmount
alias rc_bank_mount!="umount $RC"

#### List files
alias rc_bank_list="ls $RC/VIDEO"

#### Remove WAV files
alias rc_bank_clean="rm $RC/VIDEO/*.AVI"

#### Convert Files
alias rc_bank_process="$USCRIPTS/rc_bank_process $RC/VIDEO $BNK/rc"

## VPN

### Connect to VPN
alias vpn_sb="nmcli con up id $sb_server_name"

### Disconnect from VPN
alias vpn_sb!="nmcli con down id $sb_server_name"

## Local Filesystem

### Mount slot to local filesystem
alias fs_sb=". $USCRIPTS/mount_sbfs $SBFS"

### Unmount slot from local filesystem
alias fs_sb!="fusermount -u $SBFS"

## Tmux

### Start session
alias sb=". $TSESSIONS/sb.session"

### Kill session
alias sb!="tmux kill-session -t sb"

## Docker

### m4b-tool
alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt sandreas/m4b-tool:latest'

