#!/bin/zsh

#----------------
# Name          : primary_linux_manjaro_gnome
# Description   : Shell-environment configuration for Primary build on Linux Manjaro
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Bnk directory
export BNK="/mnt/bnk"

### Start directory
export START="$BNK"

## Tools

### Snc

#### Enable unison
export AUTO_SNC_ENABLED=true

## Resources

### Linux common
source "$ZENV/linux_common"

## Boot

### Tasks
run_boot_tasks() {
  local touchscreen_id="SYNA2393:00 06CB:19AC"

  xinput disable "$touchscreen_id"
  setxkbmap -option caps:escape
  
  gsettings set org.gnome.desktop.screensaver lock-enabled true
  gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "nothing"
  gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 10000

  delay_for_ui 2
  xdotool key Escape

  m_bnk
  gnome-terminal --window --maximize
}

