#!/bin/zsh

#----------------
# Name          : primary_linux_common
# Description   : Common configuration for Primary build on Linux Lubuntu
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Files

### Open Budget spreadsheet

alias budget="spreadsheet $SNC/Finances/Budget_${THIS_YEAR}.xls"

### Open financial tabs in Chrome

alias banking="$SNC/Finances/browser_tabs_banking"

### Open Amazon Fresh tabs in Chrome

alias fresh="$SNC/Health/browser_tabs_fresh"

### Open Red Sox tabs in Chrome

alias baseball="$SNC/Games/Scripts/browser_tabs_baseball"

### Open Weight spreadsheet

alias weight="spreadsheet $SNC/Health/Diet/Weight.xlsx"

### Open Jeopardy-download page in browser

alias jeopardy_episodes="$SNC/Games/Scripts/jeopardy_episodes"

### Open Jeopardy spreadsheet

alias jeopardy_games="$SNC/Games/Scripts/jeopardy_games"

### Open Chords markdown file

chords_file="$SNC/Music/Chords.md"
alias chords="markdown $chords_file > /dev/null & vim $chords_file"

### Open music-practice spreadsheet

alias music_practice="libreoffice $SNC/Music/Practice/Music_Practice.xlsx"

### Open Nautilus in a detached process nohup process

nnautilus() { nohup nautilus "$1" </dev/null >/dev/null 2>&1 &! }

### Open Bookmarks

alias bookmarks="vim $SNC/Xyz/bookmarks.md"

## Browser

### Launch Tor

alias tor="GTK_THEME=Adwaita:light torbrowser-launcher"

### Torr

alias torr="$ZSCRIPTS/download/torr"

## Web

#### Command to open a URL in a fresh browser session

alias open_browser_url="google-chrome-stable --new-window"

### Material-Color-Picker Web Utility

alias material_colors="open_browser_url https://materialui.co/colors"

### Download YouTube Audio

yt_audio() { "$ZSCRIPTS/download/yt_audio" "$1"; }

source "$ZZSH/.secrets"

## SB

### SB root directory

export SBROOT="/home/${sb_username}"

## SSH Connections

### Connect to SB via SSH

alias ssh_sb="ssh ${sb_username}@${sb_server_name}.${sb_server_domain}"

### Connect to LB via SSH

alias ssh_lb="ssh ${lb_username}@${lb_server_domain}"

### Connect to MB via SSH

alias ssh_mb="ssh ${mb_username}@${mb_server_domain}"

## RC

### Process

#### Process pending RCs on LB over SSH

alias rc_remote_lb_process="$ZSCRIPTS/rc/rc_remote_process $lb_username $lb_server_domain '/home/$lb_username/.scripts/rc_pending_process' '/home/$lb_username/bnk/rc'"

#### Process pending RCs on MB over SSH

alias rc_remote_mb_process="$ZSCRIPTS/rc/rc_remote_process $mb_username $mb_server_domain '/home/$mb_username/.scripts/rc_pending_process' '/home/$mb_username/bnk/rc'"

#### Process all pending RCs over SSH

rc_remote_all_process() { rc_remote_lb_process; rc_remote_mb_process }

### Download

#### Download RC from LB over SSH

alias rc_remote_lb_download="$ZSCRIPTS/rc/rc_remote_download $lb_username $lb_server_domain /mnt/bnk/rc"

#### Download RC from MB over SSH

alias rc_remote_mb_download="$ZSCRIPTS/rc/rc_remote_download $mb_username $mb_server_domain /mnt/bnk/rc"

#### Download RC from both LB and MB over SSH

rc_remote_all_download() { rc_remote_lb_download; rc_remote_mb_download }

### Clean

#### Clean RC directories from MB over SSH

alias rc_remote_lb_clean="$ZSCRIPTS/rc/rc_remote_clean $lb_username $lb_server_domain /home/misigno"

#### Download RC from MB over SSH

alias rc_remote_mb_clean="$ZSCRIPTS/rc/rc_remote_clean $mb_username $mb_server_domain /home/misigno"

#### Download RC from both LB and MB over SSH

rc_remote_all_clean() { rc_remote_lb_clean; rc_remote_mb_clean }

### Record

#### Microphone

##### Single Source

alias rc_remote_record_mic="$ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 04:00:00 /home/$lb_username/bnk/rc 'USB PnP Audio Device'"

#### Phone

##### Cord Audio

alias rc_remote_record_phone="$ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 04:00:00 /home/$lb_username/bnk/rc 'USB-Audio - USB Audio Device'"

##### Microphone Audio

alias rc_remote_record_phone_mic="$ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 04:00:00 /home/$lb_username/bnk/rc 'USB-Audio - USB Audio Device' 'USB PnP Audio Device'"

#### Zoom

##### Attached to Local Session

###### Headset Audio

alias rc_remote_record_zoom_headset="$ZSCRIPTS/sound/combined_audio_sink_enable; $ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 04:00:00 /home/$lb_username/bnk/rc 'USB-Audio - USB Audio Device' 'Creation'"

###### Microphone Audio

alias rc_remote_record_zoom_mic="$ZSCRIPTS/sound/combined_audio_sink_enable; $ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve 04:00:00 /home/$lb_username/bnk/rc 'Creation' 'USB PnP Audio Device'"

##### Attach from Local Session

###### Headset Audio

alias rc_remote_record_zoom_headset_unattached="$ZSCRIPTS/sound/combined_audio_sink_enable; $ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve_unattached 08:00:00 /home/$lb_username/bnk/rc 'USB-Audio - USB Audio Device' 'Creation'"

###### Microphone Audio

alias rc_remote_record_zoom_mic_unattached="$ZSCRIPTS/sound/combined_audio_sink_enable; $ZSCRIPTS/rc/rc_remote_audio_send $lb_username $lb_server_domain_local /home/$lb_username/.scripts/rc_remote_audio_recieve_unattached 08:00:00 /home/$lb_username/bnk/rc 'Creation' 'USB PnP Audio Device'"

### Thumbs

#### Base

export RC="/mnt/rc"

#### Mount

alias rc_thumb_mount="$ZSCRIPTS/rc/rc_mount"

#### Unmount

alias rc_thumb_umount="umount $RC"

#### List files

alias rc_thumb_list="ls -lh $RC/RECORD"

#### Remove WAV files

alias rc_thumb_clean="rm $RC/RECORD/*.WAV"

#### Convert Files

alias rc_thumb_process="$ZSCRIPTS/rc/rc_thumb_process -i $RC/RECORD -o $EXTA/Lg/Audio"

### Bank

#### Mount

alias rc_bank_mount="$ZSCRIPTS/rc/rc_mount"

#### Unmount

alias rc_bank_umount="umount $RC"

#### List files

alias rc_bank_list="ls $RC/VIDEO"

#### Remove WAV files

alias rc_bank_clean="rm $RC/VIDEO/*.AVI"

#### Convert Files

alias rc_bank_process="$ZSCRIPTS/rc/rc_bank_process $RC/VIDEO $BNK/rc"

## VPN

### Connect to VPN

alias vpn_sb="nmcli con up id $sb_server_name"

### Disconnect from VPN

alias kvpn_sb="nmcli con down id $sb_server_name"

## Local Filesystem

### Mount slot to local filesystem

alias fs_sb=". $ZSCRIPTS/mount/mount_sbfs $SBFS"

### Unmount slot from local filesystem

alias kfs_sb="fusermount -u $SBFS"

## Tmux

### Start session

alias sb=". $TSESSIONS/sb.session"

### Kill session

alias ksb="tmux kill-session -t sb"

## Docker

### m4b-tool

alias m4b-tool='docker run -it --rm -u $(id -u):$(id -g) -v "$(pwd)":/mnt sandreas/m4b-tool:latest'

## Updates

### Clean and Update Debian

alias system_update="$ZSCRIPTS/environment/system_update"

