#!/bin/zsh

#----------------
# Name          : ssh_linux
# Description   : Shell-environment configuration for SB build on Linux
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$BNK"

### Add ~/bin to PATH                                                                                                                                            

export PATH="$HOME/bin:$PATH"    

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### Linux common

source "$ZENV/common_linux"

### Record RC

alias rc_record="nohup /home/misigno/.scripts/rc_record '08:00:00' '/home/misigno/bnk/rc' 'plughw:CARD=Creation,DEV=0' 'plughw:CARD=Device,DEV=0' > /dev/null 2>&1&"                                             

