#!/bin/zsh

#----------------
# Name          : work_mac_m3
# Description   : Shell-environment configuration for Work build in a MacOS Work environment with an M3 chip.
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## File system

### Secrets

source "$ZZSH/.secrets"

### Bnk directory

export BNK="$HOME/bnk"

### Start directory

export START="$HOME"

### Home

export UHOME="$HOME"

### Pictures

#### Root

export SP="$SNC/Pictures"

### Work

#### Root

export SW="$SNC/Work"

#### Code

export SWC="$SWORK/Code"

#### Documents

export SWD="$SWORK/Documents"

#### Notes

export SWN="$SWORK/Notes"

#### Screenshots

export SWS="$SWORK/Screenshots"

#### Tickets

export SWT="$SWORK/Tickets"

## Tools

### Snc

#### Enable unison

export AUTO_SNC_ENABLED=false

## Resources

### HomeBrew

eval "$(/opt/homebrew/bin/brew shellenv)"

### VS Code

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

### asdf

export PATH="$HOME/.asdf/shims:$PATH"
. /opt/homebrew/opt/asdf/libexec/asdf.sh

### Vlc

alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'

### PostgreSQL

# export PGPATH="/usr/local/opt/postgresql@12/bin"

# export LDFLAGS="-L/usr/local/opt/postgresql@12/lib"

# export CPPFLAGS="-I/usr/local/opt/postgresql@12/include"

# export PKG_CONFIG_PATH="/usr/local/opt/postgresql@12/lib/pkgconfig"

### Ruby

# export RB_ENV_PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin"

# export PATH="$RB_ENV_PATH:$PGPATH:$PATH"

# export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# export MAX_THREADS=4

### Tmux

#### Open a Debug shell using Overmind

#alias overmind_debug_web="tmux splitw -v -p 100 'sleep 1; overmind connect web' & overmind start -f Procfile.dev"

#alias overmind_debug_test="tmux splitw -v -p 100 'sleep 1; overmind connect web' & overmind start -f Procfile.test"

### Vim

#### Ensure usage of the correct CTags version

#alias ctags="`brew --prefix`/bin/ctags"

### Scripts

alias agile_ticket_create="$USCRIPTS/agile_ticket_create"
alias docker_clean="$USCRIPTS/docker_clean"
alias docker_rebuild="$USCRIPTS/docker_rebuild"
alias graphql_generate="yarn graphql:generate"
alias graphql_watch="yarn graphql:generate:watch"

## Sleep Behavior

### Prevent Sleep On Lock Screen

[[ -z `pgrep caffeinate` ]] && nohup caffeinate -d -w 1 </dev/null >/dev/null 2>&1 &!

## Boot

### Tasks

run_boot_tasks() {

}

