#!/bin/zsh

#----------------
# Name          : snc.zsh
# Description   : Aliases for navigating the Snc directory
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Directory Shortcuts

### Books
export SBOOKS="$SNC/Books"

### Desktop
export SDESK="$SNC/Desktop"

### Documents
export SDOCS="$SNC/Documents"

### Lg
export SLG="$SNC/Lg"

### Pictures
export SPHO="$SNC/Pictures"

### Screenshots
export SSHOTS="$SNC/Pictures/screenshots"

### Work
export SWORK="$SNC/Work"

### Stories
export SSTORIES="$SWORK/Stories"

### Notes
export SNOTES="$SNC/Notes"

## Vim Files

### Open Lg for this Year
alias lgyr="$ZSCRIPTS/lg_open $SLG/${THIS_YEAR}.md"

### Open Do & Lg notes split vertically
alias nlog="$ZSCRIPTS/lg_open $SLG/Do.md $SLG/Lg.md"

### Open Do Notes
alias ndo="$ZSCRIPTS/lg_open $SLG/Do.md"

### Open Lg Notes
alias nlg="$ZSCRIPTS/lg_open $SLG/Lg.md"

### Open Xy Notes
alias nxy="$ZSCRIPTS/lg_open $SLG/Xy.md"

alias lg_dm="$ZSCRIPTS/lg_dismount"

alias lg_m="$ZSCRIPTS/lg_mount $SNC"

