#!/bin/zsh

#----------------
# Name          : tools.zsh
# Description   : Aliases for miscellaneous tools
# Author        : E Fournier
# Dependencies  : zsh
#----------------

## Files

### Bookmarks
alias bookmarks="vim $SDOCS/bck/bookmarks.md"

### Open Budget spreadsheet
alias budget="spreadsheet $SDOCS/Fin/Budget_${THIS_YEAR}.xls"

### Open financial tabs in Chrome
alias banking="$SDOCS/Fin/browser_tabs_banking"

### Open Amazon Fresh tabs in Chrome
alias fresh="$SDOCS/Hlt/browser_tabs_fresh"

### Create a new agile story directory and file
alias story="$USCRIPTS/create_agile_story"

### Open Weight spreadsheet
alias weight="spreadsheet $SDOCS/Hlt/Weight.xlsx"

### Open Jeopardy-download page in browser
alias jeopardy_episodes="$SDOCS/Gme/Scripts/jeopardy_episodes"

### Open Jeopardy spreadsheet
alias jeopardy_games="$SDOCS/Gme/Scripts/jeopardy_games"

### Open Chords markdown file
chords_file="$SDOCS/Mus/Chords.md"
alias chords="markdown $chords_file > /dev/null & vim $chords_file"

### Open music-practice spreadsheet
alias music_practice="libreoffice $SDOCS/Mus/Practice/Music_Practice.xlsx"

### Open Nautilus in a detached process nohup process
nnautilus() { nohup nautilus "$1" </dev/null >/dev/null 2>&1 &! }

### Dot files

#### Command to open a URL in a fresh browser session
alias open_browser_url="google-chrome-stable --new-window"

#### Copy from current directory to $HOME
alias dot_files_to_home="cp -r .tmux .tmux.conf .vim .vimrc .zsh .zshrc $HOME"

#### Copy from $HOME to current directory
alias dot_files_from_home="cp -rv ~/.tmux ~/.tmux.conf ~/.vim ~/.vimrc ~/.zsh ~/.zshrc ."

## Web

### Material-Color-Picker Web Utility
alias material_colors="open_browser_url https://materialui.co/colors"

### Download YouTube Audio
yt_audio() { "$ZSCRIPTS/yt_audio" "$1"; }

## Sync

### SB 

### Sync with Unison
alias uni=". $ZSCRIPTS/unison_start"

## Lg

### Text

#### Mount Lg Container
alias m_lg="$USCRIPTS/m_lg"

### Audio

#### Run Audio-Lg Script
alias aud_lg="$USCRIPTS/audio_lg -i $RC/RECORD -o $EXTA/Lg/Audio"

## Browser

### Launch Tor
alias tor="GTK_THEME=Adwaita:light torbrowser-launcher"

### Torr
alias torr="$USCRIPTS/torr"

## List

### List Block Devices with UUIDs
alias lsuuid="lsblk -o NAME,FSTYPE,PARTLABEL,UUID,PARTUUID"

## Location

### Whereami
alias whereami="curl ipinfo.io"

## Cleanup

### List `._` Files
alias dotunderls="find . -name '._*' -print"

### Delete `._` Files
alias dotunderrm="find . -name '._*' -delete -print"

