#!/bin/zsh

#----------------
# Name          : windows.zsh
# Description   : Aliases for WSL environment
# # Author      : E Fournier
# Dependencies  : zsh
#----------------

# Windows Aliases

## Utilities
alias start="cmd.exe /C start"
alias vvm="bash $USCRIPTS/vvm.bash $SNC"

## Programs
alias qdir="start \"$HDOCS\\Q-Dir_State.qdr\""
alias screens="explore \"%USERPROFILE%\\snc\\Pictures\\Screenshots\""
alias nplus="/mnt/c/Program\ Files\ \(x86\)/Notepad++/notepad++.exe"

## System

### Mount
export TFS="/mnt/tfs"
alias m_tfs="sudo mount -t drvfs '\\\\tfs\\TeamCityBuilds' $TFS"
alias m_tfs!="sudo umount $TFS"

### System Edit
alias hostedit="nplus 'C:\Windows\System32\drivers\etc\hosts'"

### System Cleanup
alias tempclean="rm -rf $HOME/AppData/Local/Temp/*"

### Edit Files

#### Spectrum Paths
alias spectrumpaths="vim $SNC/Work/SpectrumPaths.md"

#### Blue Jeans Rooms
alias blu="vim $SWORK/BlueJeansRooms.md"

### Logs

#### Logs root
export LOGS="/e/Logs-Raw/"
alias logs="cd $LOGS"

#### Exceptions
export EXCEPTIONS="$LOGS/Exceptions"
alias exceptions="cd $EXCEPTIONS"

