#!/bin/zsh

# SESSION
# tmux new -s $SESSION_NAME -d "cd $SDIR; zsh"

# WINDOW
# tmux new-window "cd $SDIR; zsh"

# SPLIT VERTICAL
# tmux split-window -v "vim"

# SPLIT HORIZONTAL
# tmux split-window -h "vim"

# Get option parameters
while getopts "d:" OPTION
do
  case $OPTION in
    d)
      SDIR=$OPTARG
      ;;
  esac
done

[[ -z $SDIR ]] && SDIR="$HOME"

# Create Base Session
SESSION_NAME="Base"
tmux new -s $SESSION_NAME -d "cd $SDIR; zsh"
tmux attach -t $SESSION_NAME

