#!/bin/bash

#----------------
# Name          : mount_md_multiple
# Description   : Mounts multiple md drives with veracrypt
# Author        : E Fournier
# Dependencies  : veracrypt
# Example Usage : ./mount_md_multiple mount
#----------------

mount_md() {
  veracrypt --mount "/dev/disk/by-partuuid/$md0_uid" "/mnt/md0" --slot=20
  veracrypt --mount "/dev/disk/by-partuuid/$md1_uid" "/mnt/md1" --slot=21
}

umount_md() {
  veracrypt -t -d "/dev/disk/by-partuuid/$md0_uid"
  veracrypt -t -d "/dev/disk/by-partuuid/$md1_uid"
}

main() {
  local action="$1"
  local md0_uid="1c9472df-621b-488f-8480-65eae855ae09"
  local md1_uid="7153776b-b3aa-4607-b40c-b774d2203ed6"

  [[ "$action" == "mount" ]]   && mount_md   "$md0_uid" "$md1_uid"

  [[ "$action" == "unmount" ]] && unmount_md "$md0_uid" "$md1_uid"
}

main "$@"

